"""Initial migration.

Revision ID: 624b0cf0e944
Revises: 
Create Date: 2023-12-20 10:59:05.921433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624b0cf0e944'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
